name: Build

on:
  push:
    branches:
      - main

jobs:
  release-plz:
    name: release-plz
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: build
        run: |
          cargo build
